version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6-18
      - test-3.6-111
      - test-3.6-22

      - test-3.7-18
      - test-3.7-111
      - test-3.7-22

      - test-3.8-22
      - test-3.8-31
      - test-3.8-32

      - test-3.9-31
      - test-3.9-32

jobs:
  base: &test-template
    docker:
      - image: circleci/python:3.4-stretch-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: python version
          command: python --version

      - restore_cache:
          keys:
          - v1-js
      - restore_cache:
          keys:
          - v1-py

      - run:
          name: JS deps 
          command: cd tests && yarn
      - save_cache:
          paths:
            - ./npm
          key: v1-js

      - run:
          name: setup python
          command: |
            python3 -m venv venv 
            source venv/bin/activate
            rm -f requirements.txt
            pip install -r tests/requirements/common.txt
            pip install -r tests/requirements/django${DJANGO_VERSION}.txt
      - save_cache:
          paths:
            - ./cache/pip
          key: v1-py

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            cd tests
            ln -s ../webpack_loader webpack_loader
            coverage run --source=webpack_loader manage.py test
            coveralls

  test-3.6-18:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "18"
  test-3.6-111:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "111"
  test-3.6-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-node
    environment:
      DJANGO_VERSION: "22"

  test-3.7-18:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "18"
  test-3.7-111:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "111"
  test-3.7-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-node
    environment:
      DJANGO_VERSION: "22"

  test-3.8-22:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "22"
  test-3.8-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "31"
  test-3.8-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster-node
    environment:
      DJANGO_VERSION: "32"

  test-3.9-31:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "31"
  test-3.9-32:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster-node
    environment:
      DJANGO_VERSION: "32"
